import { useEffect, useState } from 'react'
import { Download, RefreshCw } from 'lucide-react'
import { outputs } from '../api'

export default function Outputs() {
  const [files, setFiles] = useState<any[]>([])
  const [loading, setLoading] = useState(false)

  function load() {
    setLoading(true)
    outputs.list().then((r) => setFiles(r.files)).catch(() => {}).finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [])

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Outputs</h1>
          <p className="text-muted text-sm">Files generated by agency tools.</p>
        </div>
        <button
          onClick={load}
          className="flex items-center gap-2 px-4 py-2 bg-bg border border-border hover:border-slate-400 text-slate-300 text-sm rounded-lg transition-colors"
        >
          <RefreshCw size={14} className={loading ? 'animate-spin' : ''} /> Refresh
        </button>
      </div>

      <div className="bg-sidebar border border-border rounded-xl overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-left text-xs text-muted uppercase tracking-wider">
              <th className="px-5 py-3">File</th>
              <th className="px-5 py-3">Client</th>
              <th className="px-5 py-3">Type</th>
              <th className="px-5 py-3">Date</th>
              <th className="px-5 py-3">Size</th>
              <th className="px-5 py-3"></th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {files.map((f) => (
              <tr key={f.filename} className="hover:bg-border/20 transition-colors">
                <td className="px-5 py-3 text-white font-medium">{f.filename}</td>
                <td className="px-5 py-3 text-muted">{f.client}</td>
                <td className="px-5 py-3">
                  <span className="px-2 py-0.5 bg-accent/10 text-accent text-xs rounded-full">{f.type}</span>
                </td>
                <td className="px-5 py-3 text-muted">{new Date(f.date * 1000).toLocaleDateString()}</td>
                <td className="px-5 py-3 text-muted">{(f.size / 1024).toFixed(1)} KB</td>
                <td className="px-5 py-3">
                  <a
                    href={outputs.downloadUrl(f.filename)}
                    className="flex items-center gap-1 text-accent hover:underline text-xs"
                  >
                    <Download size={12} /> Download
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {files.length === 0 && (
          <p className="text-center text-muted py-12">No output files yet.</p>
        )}
      </div>
    </div>
  )
}
